#!/usr/bin/env node
/**
 * Local Web UI dev loop without Pi TUI.
 *
 * - Watches client sources and rebuilds assets (esbuild watch)
 * - Bundles session server to ESM and starts loopback session
 * - Prints openable URL (token in query string)
 *
 * Usage:
 *   npm --workspace @bytetrue/pi-vendor run dev:web
 *   PI_VENDOR_MODELS=/path/to/models.json npm --workspace @bytetrue/pi-vendor run dev:web
 *   PI_VENDOR_NO_BROWSER=1 npm --workspace @bytetrue/pi-vendor run dev:web
 */
import * as esbuild from "esbuild";
import { copyFileSync, mkdirSync, existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { delimiter, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { homedir } from "node:os";
import { spawn } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(__dirname, "..");
const webDir = join(packageRoot, "src/web");
const clientDir = join(webDir, "client");
const outdir = join(webDir, "assets");
const sessionBundle = join(__dirname, ".dev-session.mjs");
const sessionEntry = join(packageRoot, "src/web/server/session.ts");

const repoRoot = resolve(packageRoot, "../..");

function piPackageRoot(entry) {
	if (!entry || !existsSync(entry)) return undefined;
	try {
		let current = dirname(realpathSync(entry));
		for (;;) {
			try {
				if (JSON.parse(readFileSync(join(current, "package.json"), "utf8")).name === "@earendil-works/pi-coding-agent") return current;
			} catch {
				// Walk to the next parent.
			}
			const parent = dirname(current);
			if (parent === current) return undefined;
			current = parent;
		}
	} catch {
		return undefined;
	}
}

function activePiRoot() {
	if (process.env.PI_VENDOR_PI_ROOT) return process.env.PI_VENDOR_PI_ROOT;
	for (const dir of (process.env.PATH ?? "").split(delimiter)) {
		const root = piPackageRoot(join(dir, process.platform === "win32" ? "pi.cmd" : "pi"));
		if (!root) continue;
		const pathFromRepo = relative(repoRoot, root);
		// npm puts workspace node_modules/.bin first. For dev, emulate the installed
		// Pi binary rather than the repository's peer-dependency fixture.
		if (pathFromRepo === ".." || pathFromRepo.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`)) return root;
	}
	return undefined;
}

function defaultModelsPath() {
	if (process.env.PI_VENDOR_MODELS) return resolve(process.env.PI_VENDOR_MODELS);
	const agentDir = process.env.PI_CODING_AGENT_DIR || join(homedir(), ".pi", "agent");
	return join(agentDir, "models.json");
}

async function openBrowserUrl(url) {
	return new Promise((resolveOpen) => {
		const cmd = process.platform === "darwin" ? "open" : process.platform === "win32" ? "cmd" : "xdg-open";
		const args = process.platform === "win32" ? ["/c", "start", url.replace(/&/g, "^&")] : [url];
		const child = spawn(cmd, args, { detached: true, stdio: "ignore" });
		child.unref();
		child.on("error", () => resolveOpen(false));
		setTimeout(() => resolveOpen(true), 400);
	});
}

async function buildClientOnce() {
	mkdirSync(outdir, { recursive: true });
	await esbuild.build({
		entryPoints: [join(clientDir, "app.ts")],
		bundle: true,
		minify: false,
		sourcemap: true,
		outfile: join(outdir, "app.js"),
		format: "esm",
		target: "es2022",
		platform: "browser",
	});
	copyFileSync(join(clientDir, "index.html"), join(outdir, "index.html"));
	copyFileSync(join(clientDir, "style.css"), join(outdir, "style.css"));
}

async function buildSessionBundle() {
	await esbuild.build({
		entryPoints: [sessionEntry],
		bundle: true,
		platform: "node",
		format: "esm",
		target: "node20",
		outfile: sessionBundle,
		// Only bundle local workspace TS; leave node_modules external (avoids CJS dynamic require).
		packages: "external",
		banner: {
			js: "// generated by scripts/dev-web.mjs — do not edit\n",
		},
	});
}

async function main() {
	const piRoot = activePiRoot();
	if (piRoot) {
		process.env.PI_VENDOR_PI_ROOT = piRoot;
		console.log(`[dev-web] Pi catalog: ${piRoot}`);
	} else {
		console.warn("[dev-web] Could not locate installed Pi; using workspace catalog");
	}

	const modelsPath = defaultModelsPath();
	if (!existsSync(modelsPath)) {
		mkdirSync(dirname(modelsPath), { recursive: true });
		writeFileSync(modelsPath, `${JSON.stringify({ providers: {} }, null, 2)}\n`, { mode: 0o600 });
		console.log(`[dev-web] created empty models.json at ${modelsPath}`);
	} else {
		JSON.parse(readFileSync(modelsPath, "utf8"));
		console.log(`[dev-web] models: ${modelsPath}`);
	}

	console.log("[dev-web] building client…");
	await buildClientOnce();

	const ctx = await esbuild.context({
		entryPoints: [join(clientDir, "app.ts")],
		bundle: true,
		minify: false,
		sourcemap: true,
		outfile: join(outdir, "app.js"),
		format: "esm",
		target: "es2022",
		platform: "browser",
		plugins: [
			{
				name: "copy-static",
				setup(build) {
					build.onEnd((result) => {
						if (result.errors.length) return;
						copyFileSync(join(clientDir, "index.html"), join(outdir, "index.html"));
						copyFileSync(join(clientDir, "style.css"), join(outdir, "style.css"));
						console.log("[dev-web] rebuilt assets — hard-refresh browser (Cmd/Ctrl+Shift+R)");
					});
				},
			},
		],
	});
	await ctx.watch();

	console.log("[dev-web] bundling session server…");
	await buildSessionBundle();
	const sessionMod = await import(`${pathToFileURL(sessionBundle).href}?t=${Date.now()}`);
	const noBrowser = process.env.PI_VENDOR_NO_BROWSER === "1";

	const session = await sessionMod.startVendorWebSession({
		modelsPath,
		openBrowser: noBrowser ? async () => false : openBrowserUrl,
		// Bundle rewrites import.meta.url — point assets at real src/web/assets
		assetRoot: outdir,
	});

	console.log("");
	console.log("[dev-web] Open this URL (token is in the query string):");
	console.log(session.url);
	console.log("");
	console.log("[dev-web] Edit client/* → auto rebuild, then hard-refresh.");
	console.log("[dev-web] Server TS changes: Ctrl+C and re-run dev:web.");
	console.log("[dev-web] Ctrl+C to stop.");
	console.log("");

	const shutdown = () => {
		try {
			session.stop();
		} catch {
			/* ignore */
		}
		void ctx.dispose().finally(() => process.exit(0));
	};
	process.on("SIGINT", shutdown);
	process.on("SIGTERM", shutdown);

	const result = await session.waitForResult();
	console.log("[dev-web] session ended:", result.kind);
	await ctx.dispose();
	process.exit(0);
}

main().catch((err) => {
	console.error("[dev-web] failed:", err);
	process.exit(1);
});
